name: psc_accounting_app
description: PSC Accounting Application
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  
  # Google Sign In
  google_sign_in: ^6.1.6
  
  # HTTP and networking
  http: ^1.1.0
  
  # UI and utilities
  cupertino_icons: ^1.0.2
  file_picker: ^6.1.1
  
  # Add other dependencies you're using...

dependency_overrides:
  google_sign_in_web: 0.12.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # Add your assets here if any