services:
  - type: web
    name: psc-accounting-backend
    runtime: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      # Comma-separated list of allowed frontend origins (no spaces, no trailing slashes)
      - key: ALLOWED_ORIGINS
        value: "https://psc-accounting-web.web.app,https://psc-accounting-web.firebaseapp.com,http://localhost:3000,http://127.0.0.1:3000"
