services:
  - type: web
    name: psc-accounting-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      # Add your DB credentials in Render Dashboard or here as needed
      # - key: DATABASE_URL
      #   sync: false
